<?php

/**
 * Implements hook_update_N()
 * 
 * Enables all the common modules
 */

function central_update_7001(&$sandbox) {
	$modules = array(
		'views', 
		'features', 
		'strongarm', 
		'context', 
		'pathauto', 
		'diff', 
		'libraries', 
		'jquery_update', 
		'devel', 
		'module_filter', 
		'admin_menu'
	);

	module_enable($modules, TRUE);
}

function central_update_7002(&$sandbox) {
	$modules = array(
		'jdt_content_type_article'
	);

	module_enable($modules, TRUE);
}
